---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openwebui.fullname" . }}
  labels:
    {{- include "openwebui.labels" . | nindent 4 }}
data:
  WEBUI_SECRET_KEY:  {{ randAlphaNum 12 | b64enc }}
  {{- with .Values.configuration.vllmToken }}
  OPENAI_API_KEY: {{ . | b64enc }}
  {{- end }}
{{- if .Values.route.oauth.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openwebui.fullname" . }}-proxy-session
  labels:
    {{- include "openwebui.labels" . | nindent 4 }}
data:
  session_secret: {{ randAlphaNum 32 | b64enc }}
{{- end }}
