---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aligned-granite-anythingllm
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
