FROM registry.fedoraproject.org/fedora:42

RUN dnf -y install python3-pip && \
    dnf clean all

WORKDIR /app

COPY src/requirements.txt ./

RUN python3 -m pip install --no-cache-dir -r requirements.txt

COPY src/ ./

ENTRYPOINT ["/app/ingest.py"]
CMD []
