---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: 'true'
    opendatahub.io/image-display-name: CUSTOM - AnythingLLM Workbench
    notebooks.opendatahub.io/oauth-logout-url: >-
      $dashboard_route/projects/$USER_PROJECT?notebookLogout=aligned-granite-anythingllm
    opendatahub.io/accelerator-name: ''
    openshift.io/description: 'A Custom Workbench to interact with an Aligned Granite model'
    openshift.io/display-name: 'Aligned Granite (AnythingLLM)'
    notebooks.opendatahub.io/last-image-selection: '$WORKBENCH_IMAGE'
    notebooks.opendatahub.io/last-size-selection: Standard
    opendatahub.io/username: $USER_NAME
  name: aligned-granite-anythingllm
  labels:
    app: aligned-granite-anythingllm
    opendatahub.io/dashboard: 'true'
    opendatahub.io/odh-managed: 'true'
    opendatahub.io/user: $USER_NAME
spec:
  template:
    spec:
      affinity: {}
      containers:
        - resources:
            limits:
              cpu: '4'
              memory: 16Gi
            requests:
              cpu: '2'
              memory: 10Gi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/$USER_PROJECT/aligned-granite-anythingllm/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: aligned-granite-anythingllm
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/$USER_PROJECT/aligned-granite-anythingllm/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: aligned-granite-endpoint
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                                  --ServerApp.token=''
                                  --ServerApp.password=''
                                  --ServerApp.base_url=/notebook/$USER_PROJECT/aligned-granite-anythingllm
                                  --ServerApp.quit_button=False
                                  --ServerApp.tornado_settings={"user":"$USER_NAME","hub_host":"$dashboard_route","hub_prefix":"/projects/$USER_PROJECT"}
            - name: JUPYTER_IMAGE
              value: >-
                image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/$WORKBENCH_IMAGE
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/app-root/src
              name: aligned-granite-anythingllm
          image: >-
            image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/$WORKBENCH_IMAGE
          workingDir: /opt/app-root/src
        - resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: oauth-proxy
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8443
              name: oauth-proxy
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/oauth/config
              name: oauth-config
            - mountPath: /etc/tls/private
              name: tls-certificates
          image: >-
            registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4bef31eb993feb6f1096b51b4876c65a6fb1f4401fee97fa4f4542b6b7c9bc46
          args:
            - '--provider=openshift'
            - '--https-address=:8443'
            - '--http-address='
            - '--openshift-service-account=aligned-granite-anythingllm'
            - '--cookie-secret-file=/etc/oauth/config/cookie_secret'
            - '--cookie-expire=24h0m0s'
            - '--tls-cert=/etc/tls/private/tls.crt'
            - '--tls-key=/etc/tls/private/tls.key'
            - '--upstream=http://localhost:8888'
            - '--upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
            - '--email-domain=*'
            - '--skip-provider-button'
            - >-
              --openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"$WORKBENCH_IMAGE","namespace":"$USER_PROJECT"}
            - >-
              --logout-url=$dashboard_route/projects/$USER_PROJECT?notebookLogout=$WORKBENCH_IMAGE
      enableServiceLinks: false
      serviceAccountName: aligned-granite-anythingllm
      tolerations:
        - effect: NoSchedule
          key: notebooksonly
          operator: Exists
      volumes:
        - name: aligned-granite-anythingllm
          persistentVolumeClaim:
            claimName: aligned-granite-anythingllm
        - name: oauth-config
          secret:
            defaultMode: 420
            secretName: aligned-granite-anythingllm-oauth-config
        - name: tls-certificates
          secret:
            defaultMode: 420
            secretName: aligned-granite-anythingllm-tls
  readyReplicas: 1
