---
apiVersion: v2
name: open-source-ai-your-way
description: A Helm chart to deploy a customizable RAG stack
type: application
version: 0.3.2
appVersion: 0.1.0

dependencies:
  - name: milvus
    version: 4.2.48
    repository: https://zilliztech.github.io/milvus-helm
    condition: milvus.enabled
  - name: cloudnative-pg
    alias: cloudnativePg
    version: 0.23.2
    repository: https://cloudnative-pg.github.io/charts
    condition: cloudnativePg.enabled
  - name: vllm
    version: 0.2.2
    repository: https://rhai-code.github.io/vllm
    condition: vllm.enabled
  - name: vllm
    alias: vllm-embeddings
    version: 0.2.2
    repository: https://rhai-code.github.io/vllm
    condition: vllm-embeddings.enabled
  - name: openwebui
    version: 0.1.1
    repository: https://rhai-code.github.io/openwebui
    condition: openwebui.enabled
  - name: anythingllm
    version: 0.1.3
    repository: https://rhai-code.github.io/anythingllm
    condition: anythingllm.enabled
