---
vllm:
  enabled: false

vllm-embeddings:
  enabled: false

openwebui:
  enabled: false

anythingllm:
  enabled: true
  configuration:
    vllmEndpoint: http://qwen-3-8b.model-serving.svc:8000/v1
    vllmModel: Qwen/Qwen3-8B-FP8
    env:
      EMBEDDING_BASE_PATH: http://bge-m3.model-serving.svc:8000/v1
