---
vllm:
  enabled: false

vllm-embeddings:
  enabled: false

openwebui:
  configuration:
    vllmEndpoint: http://qwen-3-8b.model-serving.svc:8000/v1
    env:
      RAG_OPENAI_API_BASE_URL: http://be3-m3.model-serving.svc:8000/v1
