---
vllm:
  enabled: true
  deploymentStrategy:
    type: Recreate
  configuration:
    hfModelDownload:
      enabled: false
    modelStorage:
      type: image
      image:
        type: modelCar
        reference: quay.io/jharmison/models:qwen--qwen3-8b-modelcar
    extraArgs:
      - --served-model-name=Qwen/Qwen3-8B

vllm-embeddings:
  enabled: true
  deploymentStrategy:
    type: Recreate
  configuration:
    hfModelDownload:
      enabled: false
    modelStorage:
      type: image
      image:
        type: modelCar
        reference: quay.io/jharmison/models:intfloat--multilingual-e5-large-modelcar
    extraArgs:
      - --served-model-name=intfloat/multilingual-e5-large
      - --enforce-eager

milvus:
  enabled: false
  cluster:
    enabled: false

  etcd:
    enabled: false

  pulsarv3:
    enabled: false

  minio:
    enabled: false
    tls:
      enabled: false

  extraConfigFiles:
    user.yaml: |+
      etcd:
        use:
          embed: true
        data:
          dir: /var/lib/milvus/etcd
      common:
        storageType: local

cloudnative-pg:
  enabled: false
  crds:
    create: false
  config:
    clusterWide: false
  containerSecurityContext:
    runAsUser: null
    runAsGroup: null
