---
vllm:
  enabled: true
  deploymentStrategy:
    type: Recreate
  configuration:
    hfModelDownload:
      enabled: false
    modelStorage:
      type: image
      image:
        type: modelCar
        reference: quay.io/jharmison/models:qwen--qwen3-8b-modelcar
    extraArgs:
      - --served-model-name=Qwen/Qwen3-8B

vllm-embeddings:
  enabled: true
  deploymentStrategy:
    type: Recreate
  configuration:
    hfModelDownload:
      enabled: false
    modelStorage:
      type: image
      image:
        type: modelCar
        reference: quay.io/jharmison/models:baai--bge-m3-modelcar
    extraArgs:
      - --served-model-name=BAAI/bge-m3
      - --enforce-eager

milvus:
  enabled: true
  cluster:
    enabled: false

  etcd:
    enabled: false

  pulsarv3:
    enabled: false

  minio:
    enabled: false
    tls:
      enabled: false

  extraConfigFiles:
    user.yaml: |+
      etcd:
        use:
          embed: true
        data:
          dir: /var/lib/milvus/etcd
      common:
        storageType: local

  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 5
  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 5
    failureThreshold: 10
  standalone:
    persistence:
      annotations:
        helm.sh/resource-policy: null
      persistentVolumeClaim:
        size: 5Gi

# Note: only set this to enabled if you need to install the operator!
cloudnativePg:
  enabled: false
  operand:
    enabled: false # If the operator is installed, set this to true to enable using it
    replicas: 1
    size: 5Gi
    dbName: opensourceai
    credentials:
      user: opensourceai
      password: opensourceai
  crds:
    create: true
  config:
    clusterWide: false
  containerSecurityContext:
    runAsUser: null
    runAsGroup: null

openwebui:
  enabled: true
  configuration:
    vllmEndpoint: http://open-source-ai-vllm:8000/v1
    vllmModel: Qwen/Qwen3-8B
    env:
      VECTOR_DB: milvus
      MILVUS_URI: http://root:Milvus@open-source-ai-milvus:19530
      MILVUS_INDEX_TYPE: AUTOINDEX
      RAG_EMBEDDING_ENGINE: openai
      RAG_EMBEDDING_MODEL: BAAI/bge-m3
      RAG_OPENAI_API_BASE_URL: http://open-source-ai-vllm-embeddings:8000/v1
      RAG_OPENAI_API_KEY: fake

anythingllm:
  enabled: false
  configuration:
    vllmEndpoint: http://open-source-ai-vllm:8000/v1
    vllmModel: Qwen/Qwen3-8B
    env:
      EMBEDDING_ENGINE: generic-openai
      EMBEDDING_MODEL_PREF: BAAI/bge-m3
      EMBEDDING_MODEL_MAX_CHUNK_LENGTH: 8192
      EMBEDDING_BASE_PATH: http://open-source-ai-vllm-embeddings:8000/v1
      GENERIC_OPEN_AI_EMBEDDING_API_KEY: fake
      VECTOR_DB: milvus
      MILVUS_ADDRESS: http://open-source-ai-milvus:19530
      MILVUS_USERNAME: root
      MILVUS_PASSWORD: Milvus
