---
vllm:
  enabled: false

vllm-embeddings:
  enabled: false

openwebui:
  enabled: false

anythingllm:
  enabled: true
  route:
    oauth:
      enabled: false
  configuration:
    vllmEndpoint: http://llama-32-3b.model-serving.svc:8000/v1
    vllmModel: RedHatAI/Llama-3.2-3B-Instruct-FP8
    env:
      EMBEDDING_BASE_PATH: http://bge-m3.model-serving.svc:8000/v1
